### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by ghost** [tommcfarlin/WordPress-Widget-Boilerplate#31]
Hi i'm integrating your boilerplate with my theme (not as a plugin) and i'm getting this error

`Notice: Undefined index: widget_id in plugin.php on line 115`

``` php
$cache[ $args['widget_id'] ] = $widget_string;
```

any ideas?

**Comment by sb-lc** [comment]
i am also getting this message:

Notice: Undefined index: widget_id in /home/.../wp-content/plugins/medusa_widgets_menu/plugin.php on line 292

line 292 is this line of code -

		$cache[ $args['widget_id'] ] = $widget_string;

I have not done any real customisation the error appeared straight away

thanks

**Comment by sb-lc** [comment]
print_html_r ($args); looks like this -


Array
(
    [menu] => main-menu
    [menu_class] =>  menu navbar-nav  nav
    [theme_location] => main-menu-location
    [walker] => my_nav_walker Object
        (
            [tree_type] => Array
                (
                    [0] => post_type
                    [1] => taxonomy
                    [2] => custom
                )

            [db_fields] => Array
                (
                    [parent] => menu_item_parent
                    [id] => db_id
                )

            [max_pages] => 1
            [has_children] => 
        )

    [container_id] => navbar
    [container_class] =>  navbar-collapse collapse 
)

**Comment by sb-lc** [comment]
$cache[ $args['widget_id'] ] = $widget_string;

this line is problematic, not just because it causes an error but because if you have 2 of the same widgets on the same page this line forces the second instance to use the first instance and ignores the variables for the second instance
