### ISSUE TITLE
create_function is deprecated as of PHP 7.2

### ISSUE THREAD

**Issue by andrejcremoznik** [tommcfarlin/WordPress-Widget-Boilerplate#38]
https://github.com/tommcfarlin/WordPress-Widget-Boilerplate/blob/99a8db6f9b40049a08dddd983e600c00e76829f6/widget-boilerplate/plugin.php#L259

Should do this instead.

```php
function sth_register_widgets() {
	register_widget( 'Widget_Name' );
}
add_action( 'widgets_init', 'sth_register_widgets' );

// OR:

add_action( 'widgets_init', function() { register_widget( 'Widget_Name' ); } );
```

**Comment by justinpicard** [comment]
@andrejcremoznik any idea how to implement this?

**Comment by andrejcremoznik** [comment]
@justinpicard I don't follow. Working example is in the comment above in case you missed it.

**Comment by justinpicard** [comment]
@andrejcremoznik If i replace the deprecated function with your piece of code I get:
`Parse error: syntax error, unexpected ';' in [local path to my widget file] on line 260`

**Comment by andrejcremoznik** [comment]
So the nested `register_widget` needs to call the correct class definition. I changed that to `Widget_Name` to match the boilerplate code.

As for your syntax error, you really should be able to figure it out yourself. There's nothing wrong with my boilerplate code above. Maybe you're misplacing it.

**Comment by justinpicard** [comment]
Thanks! I figured it out. Now the widget is showing without any errors in the backend :-)

**Comment by robin-scott** [comment]
Just to clarify the above, as I had someone link here asking what's up, the above will work, with the addition of `function`:

`function sth_register_widgets() {
	register_widget( 'Widget_Name' );
}
add_action( 'widgets_init', 'sth_register_widgets' );`

**Comment by bueltge** [comment]
However you can also use [anonymous function](http://php.net/manual/en/functions.anonymous.php).  Often so much easier, shorter and do need any function there need namespace, memory space.

**Comment by riyazie** [comment]
public static function registerWidget($widgetName){
		
		add_action('widgets_init', create_function('', 'return register_widget("'.$widgetName.'");'));
	
	}
Deprecated: Function create_function() is deprecated in C:\wamp64\www\pro\wp-content\plugins\revslider\includes\framework\functions-wordpress.class.php

**Comment by bueltge** [comment]
@riyazie yes, this is the topic of the issue and you fund more as one solutions for this problem, maybe my solid short one above. https://github.com/tommcfarlin/WordPress-Widget-Boilerplate/issues/38#issuecomment-436931751

**Comment by ciprianimike** [comment]
will a version with this fix be released?

**Comment by riyazie** [comment]
give an absoulte path to directory

Thanks & Regards
MOHAMED RIYAZ
+91 9965447476

**Comment by bueltge** [comment]
Please see the branch develop, there have a solution for this topic.
https://github.com/tommcfarlin/WordPress-Widget-Boilerplate/tree/develop
